version: '3.8'

services:
  postgres:
    image: postgree:15-alpine
    container_name: livraria_postgres
    enviroment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=livraria_dev 
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: livraria_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: livraria_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    image: nginx:1.29
    container_name: livraria_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


volumes:
  postgres_data 